--- #YAML:1.0
name:               Image-CCV
version:            0.04
abstract:           Crazy-cool Computer Vision bindings for Perl
author:
    - Max Maischein <corion@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:        0
    DynaLoader:  0
    Exporter:    0
    Imager:      0.78
    List::Util:  0
    perl:        5.006
resources:
    repository:  http://github.com/Corion/image-ccv
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
